In [643]:
import numpy as np
import pandas as pd
import itertools
from numba import jit, prange
import json

try:
    df # does a exist in the current namespace
except NameError:
#     df = pd.read_csv(r'diabetes.csv')
#     Dataset kaggle
#     https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction
#     df = pd.read_csv(r'heart2.csv')
    
#     dfa = pd.read_csv(r'heart2.csv')
    dfa = pd.read_csv(r'heart4.csv')
    dfa["Sex2"] = np.nan
    dfa["ChestPainType2"] = np.nan

    for i in range(dfa.shape[0]):
        if dfa["Sex"][i] == "M":
            dfa["Sex2"][i] = 0
        else:
            dfa["Sex2"][i] = 1

        if dfa["ChestPainType"][i] == "ASY":
            dfa["ChestPainType2"][i] = 0
        elif dfa["ChestPainType"][i] == "NAP":
            dfa["ChestPainType2"][i] = 1
        elif dfa["ChestPainType"][i] == "NAP":
            dfa["ChestPainType2"][i] = 2
        else:
            dfa["ChestPainType2"][i] = 3

    dfa = dfa[['Age', 'RestingBP', 'MaxHR', 'HeartDisease']].copy()
    
    randlist = pd.read_csv('foo4.csv', sep=',', header=None)
    dfa['rand'] = randlist
    dfa = dfa.copy()
    
    df = dfa[dfa['RestingBP'] > 0].copy()
    dfa1 = pd.DataFrame([[30,190,65,1,0]], columns=['Age','RestingBP','MaxHR', 'HeartDisease', 'rand'])
    dfa2 = pd.DataFrame([[30,190,120,1,0]], columns=['Age','RestingBP','MaxHR', 'HeartDisease', 'rand'])
    dfa3 = pd.DataFrame([[30,190,170,1,0]], columns=['Age','RestingBP','MaxHR', 'HeartDisease', 'rand'])
    dfa4 = pd.DataFrame([[70,190,62,0,0]], columns=['Age','RestingBP','MaxHR', 'HeartDisease', 'rand'])
    
    dfa5 = pd.DataFrame([[30,190,65,1,1]], columns=['Age','RestingBP','MaxHR', 'HeartDisease', 'rand'])
    dfa6 = pd.DataFrame([[30,190,120,1,1]], columns=['Age','RestingBP','MaxHR', 'HeartDisease', 'rand'])
    dfa7 = pd.DataFrame([[30,190,170,1,1]], columns=['Age','RestingBP','MaxHR', 'HeartDisease', 'rand'])
    dfa8 = pd.DataFrame([[70,190,62,0,1]], columns=['Age','RestingBP','MaxHR', 'HeartDisease', 'rand'])
    
    
    df = df.append(dfa1, ignore_index = True)
    df = df.append(dfa2, ignore_index = True)
    df = df.append(dfa3, ignore_index = True)
    df = df.append(dfa4, ignore_index = True)
    df = df.append(dfa5, ignore_index = True)
    df = df.append(dfa6, ignore_index = True)
    df = df.append(dfa7, ignore_index = True)
    df = df.append(dfa8, ignore_index = True)
    

    catvalues = [3, 3, 3, 2, 2]
    
    
#     df = pd.DataFrame(np.random.random((1000,4)), columns=['Column 1', 'Column 2', 'Column 3', 'Column 4'])
#     df = df.copy()
#     catvalues = [3, 3, 3, 2]
    

try:
    G # does a exist in the current namespace
except NameError:
#     G = [[1,2,3,4]]
    G = [[i+1 for i in range(df.shape[1])]]
    
try:
    E # does a exist in the current namespace
except NameError:
#     E = [[1,2], [1,3], [1,4], [2,3], [2,4], [3,4]]
    E = [[i,j] for i in range(1, df.shape[1]) for j in range(i+1, df.shape[1]+1)]
    
try:
    icounter # does a exist in the current namespace
except NameError:
    icounter = 0
    
try:
    ptable # does a exist in the current namespace
except NameError:
    ptable = []

    
try:
    completepvaltable # does a exist in the current namespace
except NameError:
    completepvaltable = []
    
try:
    graphSequence # does a exist in the current namespace
except NameError:
    graphSequence = []    

try:
    gFlag # does a exist in the current namespace
except NameError:
    gFlag = 0   
    
try:
    mleList # does a exist in the current namespace
except NameError:
    mleList = []   
    
try:
    GStatList # does a exist in the current namespace
except NameError:
    GStatList = []   
    
try:
    GStatPValueList # does a exist in the current namespace
except NameError:
    GStatPValueList = []   
    
try:
    rankList # does a exist in the current namespace
except NameError:
    rankList = []   
    
try:
    stopalgo # does a exist in the current namespace
except NameError:
    stopalgo = False   
    
print("gFlag =", gFlag)
e = E[icounter]
# print("e =", e)

# Set G1 to G-e
# For example new G = [[234][124]], set e = [12]

if gFlag == 1:
    X = [lst for lst in G if set(e).issubset(set(lst))]
    G1 = [lst1 for lst1 in G if set(e).issubset(set(lst1)) == False]

#     print("G1 =", G1)

    setB0 = [list(set(lst) - set(e[1:])) for lst in X]
    setB1 = [list(set(lst) - set(e[:-1])) for lst in X]

    G1a = G1.copy()

    if G1a == []:
        for i in range(len(setB0)):
            G1.append(setB0[i])

        for j in range(len(setB1)):
            G1.append(setB1[j])


    for y in setB0:
        if np.sum([set(y).issubset(lst) for lst in G1]) == 0:
            G1.append(y)

    for y in setB1:
        if np.sum([set(y).issubset(lst) for lst in G1]) == 0:
            G1.append(y)
else:
    G1 = G
    
print("G1 =", G1)
print("E =", E)





gFlag = 1
G1 = [[5], [1, 2, 3], [1, 2, 4]]
E = [[1, 2], [1, 3], [1, 4], [2, 3], [2, 4], [3, 4]]


In [644]:
# print("age")
# print(df['Age'].min())
# print(df['Age'].max())
# print("restingbp")
# print(df['RestingBP'].min())
# print(df['RestingBP'].max())
# print("maxhr")
# print(df['MaxHR'].min())
# print(df['MaxHR'].max())

# print(df.shape[0])
# df['rand'] = np.random.random(df.shape[0])
# print(np.random.random(df.shape[0]))

# print(df.shape)
# randlist = pd.read_csv('foo.csv', sep=',', header=None)
# print(randlist.shape)


# a2 = np.random.random(10098)
# np.savetxt("foo4.csv", a2, delimiter=",")

# print(len(df['Age']))
# print(randlist)

# print(df)

In [645]:
# a2 = np.random.random(10098)
# np.savetxt("foo4.csv", a2, delimiter=",")

In [646]:
# Creating design matrix A and converting contingency table u into vector of counts

df2 = df.copy()
# catvalues = [2,2,2,2]
# df2 = df.copy()
n = df.shape[0]

print("n =", n)

for i in range(len(list(df.columns))):
    dfmin = df[list(df.columns)[i]].min()
    dfmax = df[list(df.columns)[i]].max()
    dfrange = (dfmax - dfmin)/catvalues[i]
#     if catvalues[i] > 2:
#         for j in range(n):
#             jval = df[list(df.columns)[i]][j]
# #             cond = [dfmin + k*dfrange <= jval < dfmin + (k+1)*dfrange if dfmin <= k <= (catvalues[k]-2) else dfmin + k*dfrange <= jval <= dfmin + (k+1)*dfrange for k in range(catvalues[i])]
#             cond = [dfmin + k*dfrange <= jval < dfmin + (k+1)*dfrange if k <= catvalues[i]-2 else dfmin + k*dfrange <= jval <= dfmin + (k+1)*dfrange for k in range(catvalues[i])]
#             df2[list(df.columns)[i]][j] = cond.index(True)
            
    for j in df.index.values.tolist():
        jval = df[list(df.columns)[i]][j]
#             cond = [dfmin + k*dfrange <= jval < dfmin + (k+1)*dfrange if dfmin <= k <= (catvalues[k]-2) else dfmin + k*dfrange <= jval <= dfmin + (k+1)*dfrange for k in range(catvalues[i])]
        cond = [dfmin + k*dfrange <= jval < dfmin + (k+1)*dfrange if k <= catvalues[i]-2 else dfmin + k*dfrange <= jval <= dfmin + (k+1)*dfrange for k in range(catvalues[i])]
        df2[list(df.columns)[i]][j] = cond.index(True)
            
            
#     else:
#         for j in range(size):
#             jval = df[list(df.columns)[i]][j]
#             cond = [dfmin + i*dfrange <= jval < dfmin + (i+1)*dfrange if dfmin <= i <= (catvalues[i]-2) else dfmin + i*dfrange <= jval <= dfmin + (i+1)*dfrange for i in range(catvalues[i])]
#             df2[list(df.columns)[i]][j] = cond.index(True)

# a,b,c = 0,0,1
idx = pd.IndexSlice

def func(lst):
#     dictvalues = {"Pregnancies": 3, "Glucose": 3, "BloodPressure": 3, "SkinThickness": 3, "Insulin": 3, "BMI": 3, "DiabetesPedigreeFunction":3, "Age":3, "Outcome": 2}
#     orderdict = {"Pregnancies": 1, "Glucose": 2, "BloodPressure": 3, "SkinThickness":4, "Insulin":5, "BMI": 6, "DiabetesPedigreeFunction": 7, "Age":  8, "Outcome": 9}
#     order2dict = {1: "Pregnancies", 2: "Glucose", 3: "BloodPressure", 4: "SkinThickness", 5: "Insulin", 6: "BMI", 7: "DiabetesPedigreeFunction", 8: "Age", 9: "Outcome"}

    dictvalues = dict([(df.columns[i], catvalues[i]) for i in range(len(df.columns))])
    orderdict = dict([(df.columns[i], i+1) for i in range(len(df.columns))])
    order2dict = dict([(i+1, df.columns[i]) for i in range(len(df.columns))])
    
    unio = list(set().union(*lst))
    unio2 = sorted(unio)
    mydict = dict(zip(unio2, list(range(len(unio2)))))

    templ = np.zeros(len(unio))
    lst2 = [list(range(1, dictvalues[order2dict[i]]+1)) for i in unio2]
    lst3 = list(itertools.product(*lst2))
    templ = np.zeros(len(lst3))
    emptylist = []

    # Creating the design matrix
    for l in lst:
        for j in list(itertools.product(*[list(range(1, dictvalues[order2dict[i]]+1)) for i in sorted(l)])):
            for k in range(len(lst3)):
                if list(j) == [lst3[k][m] for m in [mydict[n] for n in sorted(l)]]: 
                    templ[k] = 1

            emptylist.append(templ)
            templ = np.zeros(len(lst3))
    
    ltest0 = [i for i in unio2]
    ltest = [df2[j] for j in [order2dict[i] for i in unio2]]
    data_crosstab = pd.crosstab(ltest[:-1], ltest[-1], margins = False, dropna = False) # set margins = True to see margins

    return np.array(emptylist), data_crosstab



n = 10095


script_4438137881695786377:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [647]:
matrixA, utemp = func(lst = G1)

print(matrixA)
print(utemp)

# print(matrixA[0,:])
# print(np.sum(matrixA[0,:]))

# print(matrixA.ndim)

matrixA1 = ["{" + str(list(x))[1:-1] + "}" for x in matrixA]
matrixA2 = "{" + str(matrixA1)[1:-1] + "}"
matrixA3 = "{" + str(matrixA)[1:-1] + "}"

tempstr = "matrix {"
for i in range(len(matrixA)-1):
    tempstr = tempstr + "{" + str(list(matrixA[i]))[1:-1] + "}" + ", "
    
tempstr = tempstr + "{" + str(list(matrixA[len(matrixA)-1]))[1:-1] + "}}"

with open("/Users/jc/readme2", 'w') as f2:
    f2.write(tempstr)
    
f2.close()


[[1. 0. 1. ... 0. 1. 0.]
 [0. 1. 0. ... 1. 0. 1.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 1.]]
rand                              0.0  1.0
Age RestingBP MaxHR HeartDisease          
0   0         0     0               6    5
                    1               2    9
              1     0              62   59
                    1             102   85
              2     0              80   85
                    1              44   22
    1         0     0               5    6
                    1              16    6
              1     0             171  159
                    1             126  127
              2     0             332  306
                    1              51   48
    2         0     0               5    6
                    1               1    1
              1     0               6    5
                    1               1    1
              2     0              10   12
                    1      

In [648]:
# Calculating rank of design matrix A

# testA = np.array([[1,0,0], [0,1,0], [0,0,1]])
# testA1 = np.array([[1,1,1,0,0,0], [0,0,0,1,1,1], [1,0,0,1,0,0], [0,1,0,0,1,0], [0,0,1,0,0,1]])

rankModel = np.linalg.matrix_rank(matrixA, tol=None, hermitian=False)
# rankModel = np.linalg.matrix_rank(testA1, tol=None, hermitian=False)
print("rankModel =", rankModel)



rankModel = 37


In [649]:
f3 = open("/Users/jc/readme2", "r")
# print(f3.read())

In [650]:
setup();
restart;
loadPackage "FourTiTwo"
A = value get "/Users/jc/readme2"
markovBasis = toricMarkov A
print(markovBasis)
"readme5" << toString markovBasis << close
copyFile("readme5", "/Users/jc/readme5")

--initialization text already in file: ~/.profile-Macaulay2
--initialization text already in file: ~/.login-Macaulay2
--initialization text already in file, no changes needed: /Users/jc/.bash_profile
--initialization text already in file, no changes needed: /Users/jc/.zprofile
--initialization text already in file, no changes needed: /Users/jc/.login
--initialization text already in file: ~/.emacs-Macaulay2
--initialization text already in file, no changes needed: /Users/jc/.emacs


| 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  -1 -1 1 |
| 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 

In [651]:
pythonf = open("/Users/jc/readme5", "r")
x = pythonf.read()

print(G1)

# print(markovBasis)
# restart;
# print(A)
# // "readme5" << toString markovBasis << close

[[5], [1, 2, 3], [1, 2, 4]]


In [652]:
if G1 != [[i+1 for i in range(df.shape[1])]]:
    new_string = x[7:].replace("{", "[" )
    new_string2 = new_string.replace("}", "]" )

    y = json.loads(new_string2)

    print(y)
    # print(type(y))

    B = np.array(y)
    print("B =", B)
    # print(B.shape)
else:
    B = []
    
# print(B)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1, -1, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1, 0, 0, -1, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, -1, 0, -1, 0, 1], [0, 0, 0, 0, 0,


B = [[ 0  0  0 ... -1 -1  1]
 [ 0  0  0 ...  0 -1  1]
 [ 0  0  0 ... -1  0  1]
 ...
 [ 1  0 -1 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]]


In [653]:
A,u = func(lst = G1)
u = u.to_numpy()
u = u.tolist()
u = np.array([item for items in u for item in items])

# u = u*20 + 1

A1 = A.flatten()

print("A =", A)
print("u =", u)
# print("u1 =", u1)

print(np.sum(u))

A = [[1. 0. 1. ... 0. 1. 0.]
 [0. 1. 0. ... 1. 0. 1.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 1.]]
u = [  6   5   2   9  62  59 102  85  80  85  44  22   5   6  16   6 171 159
 126 127 332 306  51  48   5   6   1   1   6   5   1   1  10  12   1   1
  16  17  34  32 115 116 166 153  71  94  38  50  45  65 186 166 536 542
 756 795 387 361 165 165   4   7  60  72  39  38 147 128  37  40  28  27
   7   4  18  15  26  29  90  75   3   8  10  12  14  19 152 167 193 181
 450 441  46  31  31  57   1   1  28  38  35  42  87  89  11  11   6   5]
10095


In [654]:
# BMI vs diabetes

import random
import math
import pandas as pd
import numpy as np
from numba import jit, prange
from scipy.special import factorial

# df = pd.read_csv(r'diabetes.csv')
A,u = func(lst = G1)
u = u.to_numpy()
u = u.tolist()
u = np.array([item for items in u for item in items])
# u = u*20 + 1

if G1 != [[i+1 for i in range(df.shape[1])]]:
    Btemp = B
    B = np.concatenate((Btemp,-Btemp))

# @jit(nopython=True, parallel=True, fastmath=True)
def calcs(numsamples, A, u, B):
    avert = np.array([A[:,i] for i in range(A.shape[1])])
    a = np.zeros(numsamples)
    a3 = np.zeros(numsamples)
    for i7 in prange(numsamples):
        a[i7] = np.random.rand()
        a3[i7] = np.random.rand()

    randlist1 = a.copy()
    randlist2 = a3.copy()
    chilist = np.zeros(numsamples)
    
    p1 = np.sum(u)*np.ones(u.shape[0])/u.shape[0]  
    
    tol1 = 0.001
    adot = np.zeros(A.shape[0])
    pcalc = np.zeros(A.shape[0])
    p1tempcalc = np.zeros(A.shape[0])
    ptempcalc = np.zeros(A.shape[0])

    
    adot1 = np.dot(A,u)

    for t in range(100):
        if np.sum(np.absolute(np.dot(A,p1) - adot1)) <= tol1:
            break
        else:
            p1temp = p1.copy()
            p1 = np.array([p1temp[j] * (np.prod(np.power(adot1, avert[j])) / np.prod(np.power(np.dot(A,p1temp), avert[j])))**(1/np.sum(A[0,:])) for j in range(u.shape[0])])    
    
    chip = np.sum(np.array([((u[a1] - p1[a1])**2)/p1[a1] for a1 in range(u.shape[0])]))
    
    if G1 != [[i+1 for i in range(df.shape[1])]]:
        v = u
        for m in range(numsamples):
            w = B[int(len(B) * np.random.rand())]
            w1 = w.copy()

            tempmin = v[0] + w1[0]
            for j3 in prange(w1.shape[0]):
                if v[j3] + w1[j3] <= tempmin:
                    tempmin = v[j3] + w1[j3]

            if tempmin < 0:
                break
            else:       
                qprod = np.array([v[i] / (v[i] + w1[i]) if v[i] != v[i] + w1[i] and v[i] != 0 and (v[i] + w1[i]) != 0 else 1 for i in range(len(v))])

                q = np.prod(qprod)


                if q >= 1:
                    v = v + w1
                elif randlist2[m] <= q:
                    v = v + w1

            p = np.sum(u)*np.ones(u.shape[0])/u.shape[0]
            tol1 = 0.01
            adot = np.dot(A,v)

            for t2 in range(100):
                if np.sum(np.absolute(np.dot(A,p) - adot)) <= tol1:
                    break
                else:
                    ptemp = p.copy()
                    p = np.array([ptemp[j9] * (np.prod(np.power(adot, avert[j9])) / np.prod(np.power(np.dot(A,ptemp), avert[j9])))**(1/np.sum(A[0,:])) for j9 in range(u.shape[0])])

            chitemp = np.array([((v[b1] - p[b1])**2)/p[b1] for b1 in range(u.shape[0])])
            if np.sum(chitemp) >= chip:
                chilist[m] = 1
    
    
        return np.sum(chilist)/numsamples, p1
    
    else:
        return 1, p1

# if G1 != [[1,2,3,4]]:
#     pval = calcs(100, A, np.array(u), B)[0]
# else:
#     pva1l = 1
    
pval, mleG = calcs(10000, A, np.array(u), B)

# print("mleG =", mleG)



In [655]:
# Now calculate the G^2 statistic
from scipy.stats.distributions import chi2

if G1 != [[i+1 for i in range(df.shape[1])]]:
#     print("mleG =", mleG/np.sum(mleG))
#     print("mleList[-1] =", mleList[-1]/np.sum(mleList[-1]))
    
    mleG1 = mleG
#     mleG1 = mleG/np.sum(mleG)
    mleList1 = mleList[-1]
#     mleList1 = mleList[-1]/np.sum(mleList[-1])
    
    print(mleList1)
    print(mleG1)

    
#     mleG1[i]
#     mleList1[i]
    
    
#     GSquared = np.sum([mleG[i] * np.log(mleG[i] / mleList[-1][i]) for i in range(len(mleG))])
    GSquared = 2*np.sum([mleList1[i] * np.log(mleList1[i] / mleG1[i]) for i in range(len(mleG1))])
    print("G squared =", GSquared)
    GStatList.append(GSquared)
    rankDiff = rankList[-1] - rankModel
    
    print("rankDiff =", rankDiff)
    
    pvalG = chi2.sf(GSquared, rankDiff)
    
    if pvalG * len(E) > 1:
        pvalGBonf = 1
    else:
        pvalGBonf = pvalG * len(E)
    
#     pvalGBonf = pvalG * len(E)
    
    
    
    print("pvalG =", pvalG)
else:
    mleList.append(mleG)
    rankList.append(rankModel)



[  5.51253215   5.48747023   5.51253215   5.48747023  60.63784498
  60.36216394  93.71303072  93.28697822  82.6879689   82.31204022
  33.07518936  32.92481789   5.51253215   5.48747023  11.02506384
  10.97494001 165.37593096 164.62407364 126.78821574 126.21179179
 319.72678729 318.27319653  49.61278285  49.38722564   5.51253215
   5.48747023   1.00227867   0.99772196   5.51253215   5.48747023
   1.00227867   0.99772196  11.02506384  10.97494001   1.00227867
   0.99772196  16.53759537  16.46240962  33.07518936  32.92481789
 115.76315413 115.236854   159.86340025 159.13660484  82.6879689
  82.31204022  44.10025173  43.89975643  55.12531393  54.87469481
 176.40099234 175.59901121 540.22800302 537.77193594 777.26680381
 773.73307473 374.85209189 373.14788205 165.37593096 164.62407364
   5.51253215   5.48747023  66.150376    65.84963305  38.58772057
  38.41228718 137.8132773  137.18672952  38.58772057  38.41228718
  27.5626581   27.43734854   5.51253215   5.48747023  16.53759537
  16.462409

In [656]:
print("G1 =", G1)

if G1 != [[i+1 for i in range(df.shape[1])]]: 
    ptable.append([G1, e, pval, pvalG, rankModel, mleG, pvalGBonf])
    completepvaltable.append([G1, e, pval, pvalG, '', '', pvalGBonf])

#     print(ptable)

    if icounter == (len(E)-1):
        # From the p-value table, select the edge with the highest p-value above alpha = 0.05
        ptable1 = [lst[6] for lst in ptable]
#         ptable1 = [lst[6] for lst in ptable]

#         if ptable[ptable1.index(max(ptable1))][2] > 0.05:
        if ptable[ptable1.index(max(ptable1))][6] > 0.05:    
            print("edge removed is", ptable[ptable1.index(max(ptable1))][1])

#             graphSequence.append([ptable[ptable1.index(max(ptable1))][1], ptable[ptable1.index(max(ptable1))][0], ptable[ptable1.index(max(ptable1))][2]])
            graphSequence.append([ptable[ptable1.index(max(ptable1))][1], ptable[ptable1.index(max(ptable1))][0], ptable[ptable1.index(max(ptable1))][2], ptable[ptable1.index(max(ptable1))][3], ptable[ptable1.index(max(ptable1))][6]])
            completepvaltable.append(['', '', '', '', ptable[ptable1.index(max(ptable1))][1], ptable[ptable1.index(max(ptable1))][0], ''])

            E.remove(ptable[ptable1.index(max(ptable1))][1])
            print("new E =", E)
            icounter = 0
            print("G =", ptable[ptable1.index(max(ptable1))][0])
            G = ptable[ptable1.index(max(ptable1))][0]
            rankList.append(ptable[ptable1.index(max(ptable1))][4])
            mleList.append(ptable[ptable1.index(max(ptable1))][5])
            ptable = []

            if E == []:
                print("Stop algorithm")
                print("Resulting graph is", G)
                print("Complete p-value table =", completepvaltable)
                stopalgo = True

        else:
            print("Complete p-value table =", completepvaltable)
            print("Stop algorithm")
            print("Resulting graph is", G)
            stopalgo = True
            # print(ptable)

    else:
        icounter += 1
    #     %run sbf.ipynb

    # print(ptable)


G1 = [[5], [1, 2, 3], [1, 2, 4]]
Complete p-value table = [[[[1, 3, 4, 5], [2, 3, 4, 5]], [1, 2], 0.0012, 5.3550010300686435e-79, '', '', 5.355001030068644e-78], [[[1, 2, 4, 5], [2, 3, 4, 5]], [1, 3], 0.0022, 5.411375727562375e-126, '', '', 5.411375727562375e-125], [[[1, 2, 3, 5], [2, 3, 4, 5]], [1, 4], 0.0013, 2.640773577205543e-71, '', '', 2.640773577205543e-70], [[[1, 2, 3, 4], [2, 3, 4, 5]], [1, 5], 0.0019, 0.4536803437336909, '', '', 1], [[[1, 2, 4, 5], [1, 3, 4, 5]], [2, 3], 0.0022, 1.1690204455602312e-15, '', '', 1.1690204455602312e-14], [[[1, 2, 3, 5], [1, 3, 4, 5]], [2, 4], 0.002, 6.534466415502806e-25, '', '', 6.534466415502806e-24], [[[1, 2, 3, 4], [1, 3, 4, 5]], [2, 5], 0.0067, 0.37263846100252523, '', '', 1], [[[1, 2, 3, 5], [1, 2, 4, 5]], [3, 4], 0.0019, 2.4925341193814825e-169, '', '', 2.4925341193814825e-168], [[[1, 2, 3, 4], [1, 2, 4, 5]], [3, 5], 0.0019, 0.15188216012095898, '', '', 1], [[[1, 2, 3, 4], [1, 2, 3, 5]], [4, 5], 0.0006, 0.23319969097312337, '', '', 1], ['

In [657]:
if G1 != [[i+1 for i in range(df.shape[1])]]:
#     dfGsequence = pd.DataFrame({'Edge deleted': [i[0] for i in graphSequence], 'Resulting graph': [i[1] for i in graphSequence], 'p-value': [i[2] for i in graphSequence]})
    dfGsequence = pd.DataFrame({'Edge deleted': [i[0] for i in graphSequence], 'Resulting graph': [i[1] for i in graphSequence], 'p-value': [i[2] for i in graphSequence], 'p-value G^2': [i[3] for i in graphSequence], 'p-value G^2 Bonf': [i[4] for i in graphSequence]})



    dfpvalue = pd.DataFrame({'G-e': [i[0] for i in completepvaltable], 'e': [i[1] for i in completepvaltable], 'p-value': [i[2] for i in completepvaltable], 'p-value G^2': [i[3] for i in completepvaltable], 'Delete edge': [i[4] for i in completepvaltable], 'Resulting graph': [i[5] for i in completepvaltable], 'Bonf p-value G^2': [i[6] for i in completepvaltable]})

    print(dfpvalue.to_string())
    print(dfGsequence.to_string())
else:
    gFlag = 1
    
print(gFlag)

                                             G-e       e p-value p-value G^2 Delete edge               Resulting graph Bonf p-value G^2
0                   [[1, 3, 4, 5], [2, 3, 4, 5]]  [1, 2]  0.0012         0.0                                                        0.0
1                   [[1, 2, 4, 5], [2, 3, 4, 5]]  [1, 3]  0.0022         0.0                                                        0.0
2                   [[1, 2, 3, 5], [2, 3, 4, 5]]  [1, 4]  0.0013         0.0                                                        0.0
3                   [[1, 2, 3, 4], [2, 3, 4, 5]]  [1, 5]  0.0019     0.45368                                                          1
4                   [[1, 2, 4, 5], [1, 3, 4, 5]]  [2, 3]  0.0022         0.0                                                        0.0
5                   [[1, 2, 3, 5], [1, 3, 4, 5]]  [2, 4]   0.002         0.0                                                        0.0
6                   [[1, 2, 3, 4], [1, 3, 4, 5]]

In [658]:
if stopalgo == True:
    dfpvalue.to_csv('fresults.csv', index=False)
    xd = pd.read_csv('fresults.csv', sep=',')
    print(xd.to_string())

                                             G-e       e  p-value    p-value G^2 Delete edge               Resulting graph  Bonf p-value G^2
0                   [[1, 3, 4, 5], [2, 3, 4, 5]]  [1, 2]   0.0012   5.355001e-79         NaN                           NaN      5.355001e-78
1                   [[1, 2, 4, 5], [2, 3, 4, 5]]  [1, 3]   0.0022  5.411376e-126         NaN                           NaN     5.411376e-125
2                   [[1, 2, 3, 5], [2, 3, 4, 5]]  [1, 4]   0.0013   2.640774e-71         NaN                           NaN      2.640774e-70
3                   [[1, 2, 3, 4], [2, 3, 4, 5]]  [1, 5]   0.0019   4.536803e-01         NaN                           NaN      1.000000e+00
4                   [[1, 2, 4, 5], [1, 3, 4, 5]]  [2, 3]   0.0022   1.169020e-15         NaN                           NaN      1.169020e-14
5                   [[1, 2, 3, 5], [1, 3, 4, 5]]  [2, 4]   0.0020   6.534466e-25         NaN                           NaN      6.534466e-24
6            