In [30]:
import numpy as np
import pandas as pd
import itertools
from numba import jit, prange
import json

dfa = pd.read_csv(r'smoking_driking_dataset_Ver01.csv')
dfa["sex2"] = [0 if dfa["sex"][i] == "Male" else 1 for i in range(dfa.shape[0])]
dfa["drink2"] = [0 if dfa["DRK_YN"][i] == "N" else 1 for i in range(dfa.shape[0])]

df = dfa[['age', 'drink2']][0:5000].copy()

G1 = [[1],[2]]
E = [[i,j] for i in range(1, df.shape[1]) for j in range(i+1, df.shape[1]+1)]
    
catvalues = [3, 2]
df2 = df.copy()
n = df.shape[0]

print("n =", n)

for i in range(len(list(df.columns))):
    dfmin = df[list(df.columns)[i]].min()
    dfmax = df[list(df.columns)[i]].max()
    dfrange = (dfmax - dfmin)/catvalues[i]
            
    for j in df.index.values.tolist():
        jval = df[list(df.columns)[i]][j]
#             cond = [dfmin + k*dfrange <= jval < dfmin + (k+1)*dfrange if dfmin <= k <= (catvalues[k]-2) else dfmin + k*dfrange <= jval <= dfmin + (k+1)*dfrange for k in range(catvalues[i])]
        cond = [dfmin + k*dfrange <= jval < dfmin + (k+1)*dfrange if k <= catvalues[i]-2 else dfmin + k*dfrange <= jval <= dfmin + (k+1)*dfrange for k in range(catvalues[i])]
        df2[list(df.columns)[i]][j] = cond.index(True)
            
def func(lst):
    dictvalues = dict([(df.columns[i], catvalues[i]) for i in range(len(df.columns))])
    orderdict = dict([(df.columns[i], i+1) for i in range(len(df.columns))])
    order2dict = dict([(i+1, df.columns[i]) for i in range(len(df.columns))])
    
    unio = list(set().union(*lst))
    unio2 = sorted(unio)
    mydict = dict(zip(unio2, list(range(len(unio2)))))

    templ = np.zeros(len(unio))
    lst2 = [list(range(1, dictvalues[order2dict[i]]+1)) for i in unio2]
    lst3 = list(itertools.product(*lst2))
    templ = np.zeros(len(lst3))
    emptylist = []

    # Creating the design matrix
    for l in lst:
        for j in list(itertools.product(*[list(range(1, dictvalues[order2dict[i]]+1)) for i in sorted(l)])):
            for k in range(len(lst3)):
                if list(j) == [lst3[k][m] for m in [mydict[n] for n in sorted(l)]]: 
                    templ[k] = 1

            emptylist.append(templ)
            templ = np.zeros(len(lst3))
    
    ltest0 = [i for i in unio2]
    ltest = [df2[j] for j in [order2dict[i] for i in unio2]]
    data_crosstab = pd.crosstab(ltest[:-1], ltest[-1], margins = False, dropna = False) # set margins = True to see margins

    return np.array(emptylist), data_crosstab



n = 5000


In [31]:
matrixA, utemp = func(lst = G1)

print(matrixA)
print(utemp)

matrixA1 = ["{" + str(list(x))[1:-1] + "}" for x in matrixA]
matrixA2 = "{" + str(matrixA1)[1:-1] + "}"
matrixA3 = "{" + str(matrixA)[1:-1] + "}"

tempstr = "matrix {"
for i in range(len(matrixA)-1):
    tempstr = tempstr + "{" + str(list(matrixA[i]))[1:-1] + "}" + ", "
    
tempstr = tempstr + "{" + str(list(matrixA[len(matrixA)-1]))[1:-1] + "}}"

with open("/Users/jc/readme2age", 'w') as f2:
    f2.write(tempstr)
    
f2.close()

[[1. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1.]
 [1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]]
drink2     0     1
age               
0        720  1196
1       1226  1134
2        534   190


In [32]:
f3 = open("/Users/jc/readme2age", "r")

In [33]:
setup();
restart;
loadPackage "FourTiTwo"
A = value get "/Users/jc/readme2age"
markovBasis = toricMarkov A
print(markovBasis)
"readme5age" << toString markovBasis << close
copyFile("readme5age", "/Users/jc/readme5age")

--initialization text already in file: ~/.profile-Macaulay2
--initialization text already in file: ~/.login-Macaulay2
--initialization text already in file, no changes needed: /Users/jc/.bash_profile
--initialization text already in file, no changes needed: /Users/jc/.zprofile
--initialization text already in file, no changes needed: /Users/jc/.login
--initialization text already in file: ~/.emacs-Macaulay2
--initialization text already in file, no changes needed: /Users/jc/.emacs


| 0 0  1  -1 -1 1 |
| 1 -1 -1 1  0  0 |
| 1 -1 0  0  -1 1 |



In [34]:
pythonf = open("/Users/jc/readme5age", "r")
x = pythonf.read()

In [35]:
if G1 != [[i+1 for i in range(df.shape[1])]]:
    new_string = x[7:].replace("{", "[" )
    new_string2 = new_string.replace("}", "]" )

    y = json.loads(new_string2)

    print(y)
    # print(type(y))

    B = np.array(y)
    print("B =", B)
    # print(B.shape)
else:
    B = []
    
# print(B)

[[0, 0, 1, -1, -1, 1], [1, -1, -1, 1, 0, 0], [1, -1, 0, 0, -1, 1]]
B = [[ 0  0  1 -1 -1  1]
 [ 1 -1 -1  1  0  0]
 [ 1 -1  0  0 -1  1]]


In [36]:
A,u = func(lst = G1)
u = u.to_numpy()
u = u.tolist()
u = np.array([item for items in u for item in items])

# u = u*20 + 1

A1 = A.flatten()

print("A =", A)
print("u =", u)
# print("u1 =", u1)

print(np.sum(u))

A = [[1. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1.]
 [1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]]
u = [ 720 1196 1226 1134  534  190]
5000


In [37]:
# Age vs HeartDisease

A,u = func(lst = G1)
u = u.to_numpy()
u = u.tolist()
u = np.array([item for items in u for item in items])

Btemp = B
B = np.concatenate((Btemp,-Btemp))

# @jit(nopython=True, parallel=True, fastmath=True)
def calcs(numsamples, A, u, B):
    avert = np.array([A[:,i] for i in range(A.shape[1])])
    a = np.zeros(numsamples)
    a3 = np.zeros(numsamples)
    for i7 in prange(numsamples):
        a[i7] = np.random.rand()
        a3[i7] = np.random.rand()

    randlist1 = a.copy()
    randlist2 = a3.copy()
    chilist = np.zeros(numsamples)
    
    p1 = np.sum(u)*np.ones(u.shape[0])/u.shape[0]  
    
    tol1 = 0.001
    adot = np.zeros(A.shape[0])
    pcalc = np.zeros(A.shape[0])
    p1tempcalc = np.zeros(A.shape[0])
    ptempcalc = np.zeros(A.shape[0])

    
    adot1 = np.dot(A,u)

    while np.sum(np.absolute(np.dot(A,p1) - adot1)) > tol1:
        p1temp = p1.copy()
        p1 = np.array([p1temp[j] * (np.prod(np.power(adot1, avert[j])) / np.prod(np.power(np.dot(A,p1temp), avert[j])))**0.5 for j in range(u.shape[0])])    
    
    chip = np.sum(np.array([((u[a1] - p1[a1])**2)/p1[a1] for a1 in range(u.shape[0])]))
    
    if G1 != [[i+1 for i in range(df.shape[1])]]:
        v = u
        for m in range(numsamples):
            w = B[int(len(B) * randlist1[m])]
            w1 = w.copy()
            
            if np.min(v+w1) < 0:
                v = v
            else:       
                qprod = np.array([v[i] / (v[i] + w1[i]) if v[i] != v[i] + w1[i] and v[i] != 0 and (v[i] + w1[i]) != 0 else 1 for i in range(len(v))])

                q = np.prod(qprod)


                if q >= 1:
                    v = v + w1
                elif randlist2[m] <= q:
                    v = v + w1

            p = np.sum(u)*np.ones(u.shape[0])/u.shape[0]
            adot = np.dot(A,v)
            
            while np.sum(np.absolute(np.dot(A,p) - adot)) > tol1:
                ptemp = p.copy()
                p = np.array([ptemp[j9] * (np.prod(np.power(adot, avert[j9])) / np.prod(np.power(np.dot(A,ptemp), avert[j9])))**0.5 for j9 in range(u.shape[0])])

            chitemp = np.array([((v[b1] - p[b1])**2)/p[b1] for b1 in range(u.shape[0])])
            if np.sum(chitemp) >= chip:
                chilist[m] = 1
    
    
#         return np.sum(chilist)/numsamples, p1
        return np.sum(chilist[::100])/len(chilist[::100]), p1
    
    else:
        return 1, p1
    
pval, mleG = calcs(100000, A, np.array(u), B)

print("mleG =", mleG)
print("pval =", pval)



mleG = [ 950.33598437  965.66397676 1170.55986442 1189.43985316  359.10416074
  364.89616055]
pval = 0.266


In [38]:
np.sum([(u[i] - mleG[i])**2 / mleG[i] for i in range(len(u))])

284.9868187891361

In [39]:
o = [1,2,3,4,5,6,7,8,9]
print(o[::4])

[1, 5, 9]
